environment:
  MAVEN_OPTS : -Xmx1024g -XX:MaxPermSize=256m

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn verify -Pjava8 -Pintegration -Dnet.bytebuddy.test.travis=true
  - mvn clean cobertura:cobertura coveralls:report -Pintegration

build: off
